#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

auth_type: "permissionedWithCert"   # permissionedWithCert / permissionedWithKey / public

log:
  config_file: ../config/wx-org-solo/log.yml          # config file of logger configuration.

crypto_engine: tjfoc #crypto engine config setting, support gmssl, tencentsm and tjfoc

blockchain:
  - chainId: chain1
    genesis: ../config/wx-org-solo/chainconfig/bc1.yml
#  - chainId: chain2
#    genesis: ../config/wx-org-solo/chainconfig/bc2.yml
#  - chainId: chain3
#    genesis: ../config/wx-org-solo/chainconfig/bc3.yml
#  - chainId: chain4
#    genesis: ../config/wx-org-solo/chainconfig/bc4.yml

node:
  type: full
  org_id: wx-org.chainmaker.org
  priv_key_file: ../config/wx-org-solo/certs/wx-org.chainmaker.org/node/consensus1/consensus1.sign.key
  cert_file: ../config/wx-org-solo/certs/wx-org.chainmaker.org/node/consensus1/consensus1.sign.crt
  cert_cache_size: 1000
  cert_key_usage_check: true

net:
  provider: LibP2P
  listen_addr: /ip4/0.0.0.0/tcp/11301
  seeds:
    - "/ip4/127.0.0.1/tcp/11301/p2p/Qmbh5QRj9zMXPJH8BYkh6nPgztji3geU8fKEuuzDJ7KS5k"
  tls:
    enabled: true
    priv_key_file: ../config/wx-org-solo/certs/wx-org.chainmaker.org/node/consensus1/consensus1.tls.key
    cert_file: ../config/wx-org-solo/certs/wx-org.chainmaker.org/node/consensus1/consensus1.tls.crt

# Other txpool settings can be found in tx_Pool_config.go
txpool:
  # tx_pool type, can be single, normal, batch.
  # By default the tx_pool type is normal.
  # Note: please delete dump_tx_wal folder in storage.store_path when change tx_pool type
  pool_type: "normal"

  # Max common transaction count in tx_pool.
  # If tx_pool is full, the following transactions will be discarded.
  max_txpool_size: 50000

  # Max config transaction count in tx_pool.
  max_config_txpool_size: 10

  # Whether dump unpacked config and common transactions in queue when stop node,
  # and replay these transactions when restart node.
  is_dump_txs_in_queue: true

  # Common transaction queue num, only for normal tx_pool.
  # Note: the num should be an exponent of 2 and less than 256, such as, 1, 2, 4, 8, 16, ..., 256
  common_queue_num: 8

  # The number of transactions contained in a batch, for normal and batch tx_pool.
  # Note: make sure that block.block_tx_capacity in bc.yml is an integer multiple of batch_max_size
  batch_max_size: 100

  # Interval of creating a transaction batch, for normal and batch tx_pool, in millisecond(ms).
  batch_create_timeout: 50

rpc:
  provider: grpc
  port: 12301
  tls:
    # TLS模式:
    #   disable - 不启用TLS
    #   oneway  - 单向认证
    #   twoway  - 双向认证
    #mode: disable
    #mode: oneway
    mode: twoway
    priv_key_file: ../config/wx-org-solo/certs/wx-org.chainmaker.org/node/consensus1/consensus1.tls.key
    cert_file: ../config/wx-org-solo/certs/wx-org.chainmaker.org/node/consensus1/consensus1.tls.crt

tx_filter:
  # default(store) 0; bird's nest 1; map 2; 3 sharding bird's nest
  type: 3
  # sharding bird's nest config
  # total keys = sharding.length * sharding.birds_nest.length * sharding.birds_nest.cuckoo.max_num_keys
  sharding:
    # sharding number
    length: 5
    # sharding task timeout in seconds
    timeout: 60
    snapshot:
      type: 0
      timed:
        interval: 10
      block_height:
        interval: 10
      # file path
      path: ../data/org/tx_filter
    # bird's nest config
    birds_nest:
      # bird's nest size
      length: 10
      rules:
        # Absolute expiration time /ms
        absolute_expire_time: 30000
      cuckoo:
        # 0 Default; 1 TimestampKey
        key_type: 1
        # num of tags for each bucket, which is b in paper. tag is fingerprint, which is f in paper.
        # 4 is recommended.
        tags_per_bucket: 4
        # num of bits for each item, which is length of tag(fingerprint)
        bits_per_item: 9
        # keys number
        max_num_keys: 100
        # 0 TableTypeSingle normal single table
        # 1 TableTypePacked packed table, use semi-sort to save 1 bit per item
        # 1 is recommended
        table_type: 1
  # bird's nest config
  # total keys = birds_nest.length * birds_nest.cuckoo.max_num_keys
  birds_nest:
    # bird's nest size
    length: 10
    snapshot:
      type: 0
      timed:
        interval: 10
      block_height:
        interval: 10
      # file path
      path: ../data/org/tx_filter
    # 0 Default; 1 TimestampKey
    rules:
      # Absolute expiration time /ms
      absolute_expire_time: 30000
    cuckoo:
      # 0 Default; 1 TimestampKey
      key_type: 1
      # num of tags for each bucket, which is b in paper. tag is fingerprint, which is f in paper.
      # 4 is recommended.
      tags_per_bucket: 4
      # num of bits for each item, which is length of tag(fingerprint)
      bits_per_item: 9
      # keys number
      max_num_keys: 100
      # 0 TableTypeSingle normal single table
      # 1 TableTypePacked packed table, use semi-sort to save 1 bit per item
      # 1 is recommended
      table_type: 1

monitor:
  enabled: false
  port: 14321

pprof:
  enabled: false
  port: 24321

storage:
#  rebuild_block_height: 5
  store_path: ../data/org/ledgerData1
  encryptor: sm4    # sm4/aes
  encrypt_key: "1234567890123456" #16 bytes key
  disable_block_file_db: false
#  write_block_type: 0  # 0普通写模式，1快速写模式
#  state_cache_config:
#    life_window: 3000000000000   #key/value ttl 时间，单位 ns
#    clean_window: 1000000000
#    max_entry_size: 500
#    hard_max_cache_size: 10240   #缓存大小，单位MB
#  txexistdb_config:
#    provider: leveldb
#    leveldb_config:
#      store_path: ../data/org/txexist
  blockdb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org/blocks
  statedb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org/statedb
  historydb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org/history
  resultdb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org/result
  disable_contract_eventdb: true  #是否禁止合约事件存储功能，默认为true，如果设置为false,需要配置mysql
  contract_eventdb_config:
    provider: sql                 #如果开启contract event db 功能，需要指定provider为sql
    sqldb_config:
      sqldb_type: mysql           #contract event db 只支持mysql
      dsn: root:password@tcp(127.0.0.1:3306)/  #mysql的连接信息，包括用户名、密码、ip、port等，示例：root:admin@tcp(127.0.0.1:3306)/
debug:
  # 是否开启CLI功能，过度期间使用
  is_cli_open: true
  is_http_open: false
# Contract Virtual Machine(VM) configs
vm:
  # Golang runtime in docker container
  go:
    # Enable docker go virtual machine, default: false
    enable: false
    # Mount data path in chainmaker, include contracts, uds socks
    data_mount_path: ../data/wx-org.chainmaker.org/go
    # Mount log path in chainmaker
    log_mount_path: ../log/wx-org.chainmaker.org/go
    # Communication protocol, used for chainmaker and docker manager communication
    # 1. tcp: docker vm uses TCP to communicate with chain
    # 2. uds: docker vm uses unix domain socket to communicate with chain
    protocol: tcp
    # If use a customized VM configuration file, supplement it; else, do not configure
    # Priority: chainmaker.yml > vm.yml > default settings
    # dockervm_config_path: /config_path/vm.yml
    # Whether to print log on terminal
    log_in_console: false
    # Log level of docker vm go
    log_level: INFO

    # Grpc max send message size of the following 2 servers, Default size is 100, unit: MB
    max_send_msg_size: 100
    # Grpc max receive message size of the following 2 servers, Default size is 100, unit: MB
    max_recv_msg_size: 100
    # Grpc dialing timeout of the following 2 servers, default size is 100, uint: s
    dial_timeout: 10

    # max process num for execute original txs
    max_concurrency: 20

    #  Configs of docker runtime server (handle messages with contract sandbox)
    runtime_server:
      # Runtime server port, default 32351
      port: 32351

    # Configs of contract engine server (handle messages with contract engine)
    contract_engine:
      # Docker vm contract engine server host, default 127.0.0.1
      host: 127.0.0.1
      # Docker vm contract engine server port, default 22351
      port: 22351
      # Max number of connection created to connect docker vm service
      max_connection: 5
